export const SEARCH = 'search'
export const SEARCH_FIRST_PAGE = 'search-first-page'
export const RESPONSE_ENTITY_REPLACE = 'response-entity-replace'
export const API_SEARCH = 'api-search'
export const API_GET = 'api-get'
export const UPDATE_PROXY = 'update-proxy'
